/* ASAHKARYA — editable content, curriculum and demo records. */
const curriculum = [
 {title:'Fondasi Human Capital',topics:['Opening Session','Strategic Human Capital Management','Pengetahuan Praktis Hukum untuk CHRP']},
 {title:'Organization & Competency',topics:['Managing Organization Development Part 1','Managing Organization Development Part 2','Job Design & Job Description','Competency Based Management']},
 {title:'Hubungan Industrial',topics:['Hubungan Industrial: Sinergi Pengusaha–Pekerja','Pengantar Bidang Ketenagakerjaan','01 Perjanjian Kerja','02 Peraturan Perusahaan – PKB','03 Studi Kasus PKB','Kapita Selekta – Outsourcing, Mogok, dan Lockout','Pemutusan Hubungan Kerja','Penyelesaian Perselisihan Hubungan Industrial']},
 {title:'Learning & Performance',topics:['Managing Learning & Development 1','Managing Learning & Development 2','Pembahasan Hands-on ROTI','Performance Management']},
 {title:'Talent & Career',topics:['Talent Management','Recruitment & Selection Process','Case Study People Development','Knowledge Management','Career Management','Succession Planning']},
 {title:'Leadership & Partnership',topics:['Teknik Negosiasi','Managing Leadership Development','Managing Your People Effectively','Hubungan Kerja Sama Kemitraan','Wrap Up Hubungan Industrial']}
];
const programs = [
 {id:'hr-intensive',title:'HR Professional Intensive',short:'Build people.\nBuild the business.',category:'HR & Human Capital',format:'Live online',price:2490000,duration:'8 minggu',level:'Menengah',tag:'Program unggulan',date:'12 Okt 2026',time:'19.00–21.00 WIB',place:'Ruang live online',seats:24,modules:30,visual:'hr',outcome:'Rancang sistem pengelolaan SDM yang terhubung dengan tujuan bisnis.',project:'HR improvement roadmap untuk perusahaan jasa',skills:['Human capital strategy','Organization development','People development'],topics:curriculum.flatMap(g=>g.topics)},
 {id:'communication',title:'Communication & Presentation at Work',short:'Speak clearly.\nMake an impact.',category:'Komunikasi & Presentasi',format:'Offline',price:1500000,duration:'1 hari',level:'Semua level',tag:'Praktik langsung',date:'17 Okt 2026',time:'09.00–16.00 WIB',place:'Jakarta Selatan · venue menyusul',seats:20,modules:6,visual:'comm',outcome:'Sampaikan gagasan dengan jelas, percaya diri, dan relevan untuk audiens.',project:'Presentasi solusi bisnis 5 menit',skills:['Active listening','Business storytelling','Presentation'],topics:['Mengenali audiens dan tujuan komunikasi','Active listening & empati','Struktur pesan yang jelas','Business storytelling','Praktik presentasi dan feedback','Rencana penerapan di tempat kerja']},
 {id:'recruitment',title:'Recruitment & Interview Essentials',short:'Find the fit.\nGrow the team.',category:'HR & Human Capital',format:'Mandiri',price:349000,duration:'6 jam',level:'Pemula',tag:'Belajar fleksibel',date:'Mulai kapan saja',time:'Sesuai ritmemu',place:'Materi online',seats:null,modules:6,visual:'recruit',outcome:'Susun proses seleksi yang terstruktur, relevan, dan berorientasi kompetensi.',project:'Interview guide dan scorecard kandidat',skills:['Job requirements','Structured interview','Candidate evaluation'],topics:['Menghubungkan kebutuhan peran dan bisnis','Job description & kompetensi','Menyusun pertanyaan wawancara','Behavioral interview dengan STAR','Scorecard dan evaluasi kandidat','Studi kasus seleksi tim customer success']},
 {id:'selling',title:'Consultative Selling & Negotiation',short:'Listen first.\nSell with purpose.',category:'Selling & Business',format:'Live online',price:699000,duration:'4 sesi',level:'Semua level',tag:'Untuk tim layanan',date:'20 Okt 2026',time:'19.00–21.00 WIB',place:'Ruang live online',seats:25,modules:4,visual:'sell',outcome:'Gali kebutuhan klien dan bangun negosiasi yang menciptakan nilai.',project:'Discovery script dan proposal solusi',skills:['Needs discovery','Value proposition','Negotiation'],topics:['Customer discovery untuk bisnis jasa','Menyusun value proposition','Menangani keberatan dengan empati','Roleplay negosiasi dan tindak lanjut']},
 {id:'leadership',title:'People Leadership for New Managers',short:'Lead with empathy.\nGrow together.',category:'Leadership & People',format:'Offline',price:1500000,duration:'1 hari',level:'Menengah',tag:'Workshop',date:'24 Okt 2026',time:'09.00–16.00 WIB',place:'Jakarta Selatan · venue menyusul',seats:16,modules:5,visual:'lead',outcome:'Kelola ekspektasi, delegasikan pekerjaan, dan bangun percakapan kinerja.',project:'People development action plan',skills:['Coaching conversation','Delegation','Feedback'],topics:['Transisi dari individual contributor','Menyelaraskan ekspektasi tim','Delegasi dan coaching','Feedback yang manusiawi','Action plan kepemimpinan']},
 {id:'digital',title:'Digital Productivity for HR & Business',short:'Work smarter.\nCreate more value.',category:'Digital & Productivity',format:'Mandiri',price:249000,duration:'4 jam',level:'Pemula',tag:'Skill terapan',date:'Mulai kapan saja',time:'Sesuai ritmemu',place:'Materi online',seats:null,modules:5,visual:'digital',outcome:'Rapikan alur kerja dan gunakan tools digital untuk pekerjaan HR sehari-hari.',project:'Template workflow onboarding',skills:['Digital workflow','Data literacy','Responsible AI'],topics:['Memetakan aktivitas repetitif','Kolaborasi dokumen dan data','Dashboard kerja sederhana','AI untuk drafting dan review','Menyusun workflow onboarding']},
 {id:'business-development',title:'Business Development for Service Business',short:'Find opportunity.\nBuild lasting value.',category:'Selling & Business',format:'Live online',price:799000,duration:'4 sesi',level:'Menengah',tag:'Untuk bisnis jasa',date:'27 Okt 2026',time:'19.00–21.00 WIB',place:'Ruang live online',seats:24,modules:4,visual:'biz',outcome:'Bangun rencana pertumbuhan yang berangkat dari kebutuhan pasar.',project:'Business development canvas',skills:['Market discovery','Partnership','Growth planning'],topics:['Segmentasi dan prioritas pasar','Merancang penawaran layanan','Pipeline partnership','Rencana pertumbuhan 90 hari']},
 {id:'finance',title:'Finance for Non-Finance Professionals',short:'Read the numbers.\nMake better decisions.',category:'Selling & Business',format:'Mandiri',price:299000,duration:'5 jam',level:'Pemula',tag:'Dasar bisnis',date:'Mulai kapan saja',time:'Sesuai ritmemu',place:'Materi online',seats:null,modules:5,visual:'finance',outcome:'Baca indikator keuangan sederhana untuk menyusun keputusan operasional.',project:'Budget dan evaluasi program',skills:['Budgeting','Cost awareness','Business case'],topics:['Bahasa dasar keuangan','Pendapatan dan biaya','Membaca budget','Menyusun business case','Evaluasi biaya program']}
];
const categories=['Semua','HR & Human Capital','Komunikasi & Presentasi','Leadership & People','Selling & Business','Digital & Productivity'];
const formats=['Semua format','Mandiri','Live online','Offline'];
const people=[{name:'Nadia Putri',team:'People & Culture',progress:72,pre:60,post:85,status:'Aktif'},{name:'Raka Pratama',team:'Client Services',progress:88,pre:58,post:82,status:'Aktif'},{name:'Dewi Lestari',team:'Business Development',progress:38,pre:55,post:null,status:'Perlu pendampingan'},{name:'Fajar Hidayat',team:'People & Culture',progress:100,pre:62,post:90,status:'Selesai'}];
const quizQuestions=[{q:'Apa langkah pertama saat merancang proses rekrutmen?',options:['Mengunggah lowongan secepatnya','Menyepakati kebutuhan peran dan kompetensi','Menyalin pertanyaan wawancara lama'],correct:1,why:'Kebutuhan peran dan kompetensi menjadi dasar lowongan, metode seleksi, dan evaluasi kandidat.'},{q:'Apa manfaat pertanyaan behavioral yang terstruktur?',options:['Membandingkan bukti perilaku dengan kriteria yang konsisten','Mencari kandidat dengan jawaban paling panjang','Menghilangkan kebutuhan evaluasi'],correct:0,why:'Pertanyaan dan kriteria yang konsisten membantu mengevaluasi bukti pengalaman kandidat secara lebih terarah.'},{q:'Bagaimana menggunakan scorecard kandidat?',options:['Isi berdasarkan kesan umum saja','Ubah kriteria setelah melihat kandidat favorit','Gunakan indikator yang disepakati dan catat bukti jawaban'],correct:2,why:'Scorecard menghubungkan penilaian dengan indikator dan bukti, bukan hanya kesan pewawancara.'}];
const screenGroups={
 'Jelajahi & daftar':[['home','Beranda'],['programs','Katalog program'],['program','Detail program'],['hr-path','Jalur HRD'],['soft-skills','Jalur soft skills'],['schedule','Kalender pelatihan'],['bembi','Coach Bembi ECI'],['corporate','Corporate training'],['about','Tentang & nilai ASAH'],['consult','Konsultasi kebutuhan'],['login','Masuk / daftar'],['checkout','Pendaftaran retail'],['verify','Verifikasi sertifikat']],
 'Ruang peserta':[['learner','Dashboard peserta'],['my-learning','Kelas saya'],['classroom','Ruang belajar'],['exam','Ujian & remedial'],['assignments','Tugas & feedback'],['my-schedule','Jadwal & kehadiran'],['certificates','Sertifikat & QR'],['orders','Transaksi'],['community','Komunitas'],['assistant','Asisten belajar'],['profile','Profil & preferensi']],
 'Workspace trainer':[['trainer','Dashboard trainer'],['trainer-classes','Kelas & peserta'],['reviews','Review tugas'],['earnings','Pendapatan trainer']],
 'Workspace corporate':[['company','Dashboard perusahaan'],['team','Peserta & penugasan'],['company-reports','Laporan kompetensi'],['invoices','Invoice & TOP']],
 'Operasional':[['admin','Dashboard admin'],['manage-programs','Kelola program'],['cohorts','Batch & kehadiran'],['finance','Keuangan & bagi hasil'],['certificate-admin','Penerbitan sertifikat'],['notifications','Notifikasi'],['settings','Pengaturan platform']]
};
