/* Shared rendering and local prototype state. No credentials or real payments. */
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rupiah=n=>'Rp'+Number(n).toLocaleString('id-ID');
const getLocal=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('asah-'+key))??fallback}catch{return fallback}};
const saveLocal=(key,value)=>localStorage.setItem('asah-'+key,JSON.stringify(value));
const state={route:'home',program:'hr-intensive',category:'Semua',format:'Semua format',query:'',sort:'recommended',detailTab:'overview',homeTab:'Semua',lesson:0,lessonTab:'materi',examResult:null,examAnswers:{},checkoutDone:false,checkoutType:'retail',trainerType:'dedicated',chat:[],scheduleFormat:'Semua format',...getLocal('ui',{})};
const progress=()=>getLocal('progress',[]);const currentProgram=()=>programs.find(p=>p.id===state.program)||programs[0];
const a=(r,t,c='btn')=>`<a href="#/${r}" class="${c}">${t}</a>`;
const btn=(action,t,c='btn',extra='')=>`<button type="button" class="${c}" data-action="${action}" ${extra}>${t}</button>`;
const brand=(light=false)=>`<a href="#/home" class="brand ${light?'light':''}" aria-label="AsahKarya beranda"><span class="brand-mark"><img src="assets/asahkarya-logo.jpg" alt=""></span><span class="brand-word"><em>asah</em>karya<span style="color:var(--orange)">.</span></span></a>`;
const badge=(t,c='')=>`<span class="badge ${c}">${t}</span>`;
const bar=n=>`<div class="progress"><span style="width:${Math.max(0,Math.min(100,n))}%"></span></div>`;
const heading=(t,d,action='')=>`<div class="section-head"><div><h1>${t}</h1><p>${d}</p></div>${action}</div>`;
const sectionHead=(e,t,d,action='')=>`<div class="section-head"><div><span class="eyebrow">${e}</span><h2>${t}</h2>${d?`<p>${d}</p>`:''}</div>${action}</div>`;
const statCards=items=>`<div class="stats">${items.map(([n,t,d])=>`<div class="stat"><small>${t}</small><strong>${n}</strong>${d?`<span class="trend">${d}</span>`:''}</div>`).join('')}</div>`;
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
function visual(p){return `<div class="program-visual ${p.visual}"><span class="tiny">ASAHKARYA / PRACTICAL LEARNING</span><strong class="visual-title">${p.short.replace('\n','<br>')}</strong><span class="format-label">${p.format==='Mandiri'?'▷':p.format==='Offline'?'⌖':'◉'} ${p.format}</span><span class="visual-symbol" aria-hidden="true">${p.visual==='hr'?'HR':p.visual==='comm'?'Aa':p.visual==='recruit'?'+':p.visual==='digital'?'AI':'↗'}</span></div>`}
function programCard(p){return `<article class="card program-card"><a href="#/program?id=${p.id}">${visual(p)}<div class="program-body"><div class="row">${badge(p.tag,p.id==='hr-intensive'?'orange':'')}<small>${p.level}</small></div><h3>${p.title}</h3><div class="meta"><span>◷ ${p.duration}</span><span>▦ ${p.modules} materi</span></div><div class="program-footer"><div><small>Investasi belajar</small><div class="price">${rupiah(p.price)}</div></div><span class="round-arrow">↗</span></div></div></a></article>`}
function header(){return `<div class="prototype">PREVIEW ASAHKARYA • Harga, batch, dan data operasional merupakan contoh. ${a('guide','Lihat panduan','')}</div><header class="container topnav">${brand()}<nav class="navlinks" id="navlinks">${[['programs','Program'],['hr-path','Jalur HRD'],['corporate','Corporate'],['bembi','Mentor'],['about','Tentang']].map(([r,t])=>a(r,t,state.route===r?'active':'')).join('')}</nav><div class="actions">${a('login','Masuk','btn white')}${a('programs','Mulai belajar ↗','btn primary')}<button class="menu-toggle" aria-label="Buka menu" aria-expanded="false" data-action="mobile-menu">☰</button></div></header>`}
function footer(){return `<footer class="footer"><div class="container"><div class="footer-grid"><div>${brand()}<p>Asah Potensimu,<br>Ciptakan Karya Terbaikmu.</p><small>HR & soft skills terapan.<br>Untuk profesional dan perusahaan jasa.</small></div><div><b>Temukan program</b>${a('hr-path','HR & Human Capital','')}${a('soft-skills','Soft skills','')}${a('schedule','Jadwal pelatihan','')}${a('corporate','Corporate training','')}</div><div><b>AsahKarya</b>${a('about','Tentang kami','')}${a('bembi','Coach Bembi ECI','')}${a('consult','Konsultasi program','')}${a('guide','Panduan platform','')}</div><div><b>Ruang belajar</b>${a('learner','Dashboard peserta','')}${a('verify','Verifikasi sertifikat','')}${a('login','Workspace','')}<small>Jakarta Selatan<br>Alamat lengkap menyusul.</small></div></div><div class="footer-bottom"><span>© 2026 AsahKarya · Konsep platform pelatihan</span><span>www.asahkarya.com — domain rencana</span></div></div></footer>`}
const navSets={learner:[['learner','◫','Ringkasan'],['my-learning','▣','Kelas saya'],['my-schedule','▦','Jadwal & kehadiran'],['assignments','☷','Tugas & feedback'],['certificates','✦','Sertifikat saya'],['orders','▤','Transaksi'],['community','◎','Komunitas'],['assistant','✧','Asisten belajar'],['profile','⚙','Profil & preferensi']],trainer:[['trainer','◫','Ringkasan trainer'],['trainer-classes','▣','Kelas & peserta'],['reviews','☷','Review tugas'],['earnings','▤','Pendapatan']],company:[['company','◫','Ringkasan tim'],['team','◎','Peserta & penugasan'],['company-reports','▥','Laporan kompetensi'],['invoices','▤','Invoice & TOP']],admin:[['admin','◫','Ringkasan admin'],['manage-programs','▣','Program & kurikulum'],['cohorts','▦','Batch & kehadiran'],['finance','▤','Keuangan & trainer'],['certificate-admin','✦','Sertifikat'],['notifications','♧','Notifikasi'],['settings','⚙','Pengaturan']]};
function roleFor(route){if(['trainer','trainer-classes','reviews','earnings'].includes(route))return'trainer';if(['company','team','company-reports','invoices'].includes(route))return'company';if(['admin','manage-programs','cohorts','finance','certificate-admin','notifications','settings'].includes(route))return'admin';return'learner'}
function shell(body){const role=roleFor(state.route),label={learner:'Ruang peserta',trainer:'Workspace trainer',company:'Workspace corporate',admin:'Admin platform'}[role];const title=Object.values(screenGroups).flat().find(x=>x[0]===state.route)?.[1]||'Ruang belajar';return `<div class="app-shell"><aside class="sidebar">${brand()}<div class="workspace-name">${label}</div>${navSets[role].map(([r,i,t])=>`<a href="#/${r}" class="side-link ${state.route===r?'active':''}"><span class="navicon">${i}</span>${t}</a>`).join('')}<div class="sidebar-foot"><div class="side-promo"><b>Ruang untuk terus tumbuh.</b><p>Temukan keterampilan yang kamu butuhkan berikutnya.</p>${a('programs','Jelajahi program →','btn light small')}</div>${a('home','← Beranda AsahKarya','side-link')}${a('guide','Panduan presentasi ↗','side-link')}</div></aside><div><header class="app-top"><span><span class="crumb-label">${label} / </span><b>${title}</b></span><div class="actions">${badge('Data demo','orange')}<span class="user-name">${role==='learner'?esc(getLocal('profile',{}).name||'Nadia Putri'):role==='trainer'?'Tim Trainer':role==='company'?'Nusa Jasa':'Admin AsahKarya'}</span><span class="avatar">${role==='learner'?'NP':role==='trainer'?'TR':role==='company'?'NJ':'AK'}</span></div></header><main class="app-main" id="main">${body}</main></div></div>`}
const launcher=()=>btn('roles','◫ Jelajahi workspace','role-launcher');
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function modal(title,body){$('#modal-body').innerHTML=`<h2 style="font-size:25px">${title}</h2>${body}`;$('#modal').showModal()}
function empty(t,d,link=''){return `<div class="card empty"><span class="score" style="font-size:40px">◇</span><h3>${t}</h3><p>${d}</p>${link}</div>`}
const field=(label,input)=>{
 const existing=input.match(/\bid="([^"]+)"/);
 const id=existing?existing[1]:'field-'+label.toLowerCase().replace(/[^a-z0-9]+/g,'-');
 const control=existing?input:input.replace(/<(input|select|textarea)\b/, '<$1 id="'+id+'"');
 return `<div class="form-group"><label for="${id}">${label}</label>${control}</div>`;
};
function enrolledCard(p,n){return `<div class="card enrolled-card">${visual(p)}<div>${badge(p.format)}<h3>${p.title}</h3><small>${n}% selesai · Lanjutkan langkah berikutnya</small>${bar(n)}<div class="row"><small>${p.format==='Mandiri'?'Materi → ujian → sertifikat':p.date}</small>${a(p.id==='recruitment'?'classroom':p.format==='Mandiri'?'program?id='+p.id:'my-schedule',p.format==='Mandiri'&&p.id!=='recruitment'?'Detail program →':'Lanjutkan →','btn small')}</div></div></div>`}
function bembiBlock(){return `<div class="bembi-section"><div class="bembi-photo"><img src="assets/coach-bembi.jpg" alt="Foto Coach Bembi ECI yang disediakan AsahKarya"><div class="nameplate"><strong>Coach Bembi ECI</strong><small>Bambang Eko Cahyono · Pembina & mentor AsahKarya</small></div></div><div><span class="eyebrow">BELAJAR DARI PENGALAMAN NYATA</span><h2>Perspektif praktisi.<br>Pendekatan manusiawi.</h2><p>Bersama Coach Bembi ECI, hubungkan pengembangan manusia dengan tantangan organisasi yang sesungguhnya.</p><ul class="check-list"><li>23+ tahun pengalaman profesional, menurut profil resmi ECI.</li><li>Latar human capital, pengembangan organisasi, dan manajemen kinerja.</li><li>Director & Owner PT ECI Mitra Pengembangan.</li></ul>${a('bembi','Kenali Coach Bembi ↗','btn')}<p style="margin-top:18px"><small>Profil merujuk <a class="link" href="https://expertpride.com/tentang-expert-pride/" target="_blank" rel="noreferrer">situs resmi ECI ↗</a>. Peran di AsahKarya sesuai arahan brand.</small></p></div></div>`}
